# Generated by Django 3.0.1 on 2020-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Aadhar_Number', models.IntegerField()),
                ('Phone_Numbers', models.IntegerField()),
                ('UserName', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=10)),
                ('Area', models.CharField(max_length=10)),
            ],
        ),
    ]
