# Generated by Django 3.0.1 on 2020-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='Aadhar_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Phone_Numbers',
            field=models.BigIntegerField(),
        ),
    ]
