# Generated by Django 3.0.1 on 2020-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='MinCost',
            field=models.IntegerField(default=0),
        ),
    ]
