# Generated by Django 3.0.1 on 2020-03-14 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_crop_mincost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyerName', models.CharField(max_length=20)),
                ('FarmerName', models.CharField(max_length=20)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Cost', models.IntegerField()),
                ('Crop', models.CharField(max_length=10)),
                ('FPhone', models.BigIntegerField(default=0)),
                ('BPhone', models.BigIntegerField(default=0)),
            ],
        ),
    ]
