# Generated by Django 3.0.1 on 2020-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Aadhar_Number', models.BigIntegerField()),
                ('Type', models.CharField(max_length=15)),
                ('Phone_Numbers', models.BigIntegerField()),
                ('UserName', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=10)),
                ('Area', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=30)),
                ('Company_name', models.CharField(max_length=20)),
                ('LNO', models.CharField(max_length=10)),
                ('Company_Reg', models.CharField(max_length=10)),
            ],
        ),
    ]
