# Generated by Django 3.0.1 on 2020-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='BPhone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='FPhone',
            field=models.BigIntegerField(default=0),
        ),
    ]
